# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/helloworld.smk"
include: "rules/qc.smk"



# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/helloworld/helloworld.txt",
        "results/helloworld_docker/helloworld.txt",
        "results/multiqc/multiqc_report.html"
    default_target: True
